let obj = {
    noun: ['politics',
        'passenger',
        'conversation',
        "category",
        "agency",
        "football",
        "statement",
        "heart",
        "possibility",
        "celebration"],
    verb: ["bound",
            "sign",
            "have",
            "embrace",
            "struggle",
            "convince",
            "borrow",
            "kick",
            "weigh",
            "test"],
    adjective: ["wild",
        "nutty",
        "earthy",
        "uppity",
        "cooperative",
        "psychological",
        "pumped",
        "ludicrous",
        "comfortable",
        "fanatical"]
};

console.log(obj.verb[3]);